export const data = [
  {
    id: 1,
    title: 'Health Boss APP',
    desc: 'In a team of 4 people, we had 2 weeks to develop the Health Boss App, where you can track your meals and exercise to improve your health. I assumed the role as in the front-end developer responsible for crafting the visual aesthetics and overall appearance of our application, meticulously tailoring it to align with our specific requirements.',
    img: 'assets/healthboss.jpg',
    github: 'https://github.com/Eduardcodes/Health-Boss',
    demo: 'https://health-boss.vercel.app/',
    hastags: [
      '#NextJs',
      '#Teamwork',
      '#Tailwinds',
      '#Mongoose',
      '#Cypress',
      '#Fullstack',
      '#Figma',
    ],
  },

  {
    id: 2,
    title: 'Full stack Sayxiis',
    desc: 'App about photos for who like ONLY photos and competions, this app has mobile version and desktop, React.js for the front-end, delivering a dynamic and responsive user interface, PostgreSQL and Express for the back-end, ensuring robust data management and server-side functionality, Vanilla CSS, tailored with precision, to craft a visually appealing and distinctive aesthetic  ',
    img: 'assets/sayxiis.png',
    github: 'https://github.com/ciisiq/sayxiis',
    demo: 'None',
    hastags: [
      '#Reactjs',
      '#Figma',
      '#CSS',
      '#Fullstack',
      '#Express',
      '#Postgres',
    ],
  },

  {
    id: 3,
    title: 'Fullstack Dad Jokes',
    desc: 'App where you can genarete random quotes from API and save the ones you like in the database',
    img: 'assets/dadjokes.png',
    github: 'https://github.com/ciisiq/dad-jokes-express-mongoose',
    demo: 'None',
    hastags: [
      '#Angular',
      '#CSS',
      '#Fullstack',
      '#Mongoose',
      '#Express',
      '#Fullstack',
      '#API',
    ],
  },

  {
    id: 4,
    title: 'Fullstack Studio Ghibli Film',
    desc: 'web application where you can see the list of films of studio ghibli, save the favorites one and shere the list on the social media',
    img: 'assets/ghiblit.png',
    github: 'https://github.com/ciisiq/studying-nextjs-frontend-ghibli',
    demo: 'https://studying-nodejs-ghibli.vercel.app/',
    hastags: ['#Express', '#Nextjs', '#Fullstack', '#Mongoose', 'Tailwinds'],
  },

  {
    id: 5,
    title: 'Test News Percayso',
    desc: 'Website that fetch from API information about news from user input',
    img: 'assets/news-app.png',
    github: 'https://github.com/ciisiq/news-app',
    demo: 'https://news-percayso-test.netlify.app/',
    hastags: [
      '#ReactJs',
      '#API',
      '#PostRequest',
      '#Cypress',
      '#Netifly',
      '#SaSS',
      '#Frontend',
    ],
  },

  {
    id: 6,
    title: 'Panda memory game',
    desc: 'a simple memory game, for to show DOM manipulation',
    img: 'assets/page2.png',
    github: 'https://github.com/ciisiq/memory-game',
    demo: 'https://panda-memory-game.netlify.app/',
    hastags: '#JavaScript #DOM #game #CSS #Grid',
  },

  {
    id: 7,
    title: 'Job Tracker - School of Code',
    desc: 'Project created in 4 weeks in a team of 6 people, the main idea off this fullstack project is that other people could use to list their work without using tables or email, main main function in this project was deal with the styling, feat dark mode and did some of the testing in the backend routes and BDD frontend E2E ',
    img: 'assets/job.png',
    github: 'https://github.com/SchoolOfCode/final-project-repo-bossa-nova',
    demo: 'https://bossanova.netlify.app/',
    hastags: [
      '#ReactJs',
      '#Teamwork',
      '#Tailwinds',
      '#Jira',
      '#Agile',
      '#Cypress',
      '#Fullstack',
    ],
  },
];
